### ISSUE TITLE
component not working with browserify

### ISSUE THREAD

**Issue by fraserxu** [cezary/react-loading#1]
Hi @cezary I'm tying to use this module in my project, by I'm using browserify instead of webpack to build my js file.

Since you have define the main file from the `lib` directory `"main": "lib/react-loading.js"`, which has code to load **svg** files, that works for webpack but browserify does not know how to load it.

Can you have a fix? Or you can just update the main file to read from `dist/react-loading.js`?

**Comment by cezary** [comment]
I thought this might be a problem, there's a bit of extra umd logic added to the dist/react-loading.js file but I'll go ahead and accept your pull request.
