### ISSUE TITLE
Warning - setState({...}) on unmounted component

### ISSUE THREAD

**Issue by crobinson42** [cezary/react-loading#11]
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component.`

Here's my code:
```
componentDidMount() {
 this.fetchUsers(); // will make request to server and setState
}

render(){
    if (this.state.users.length === 0) {
      return ( <Loading type='balls' color='#e3e3e3' />);
    }
    else {
      return (
       {this.userList()}
      );
    }
}
```

When I remove  <Loading type='balls' color='#e3e3e3' /> the console warning goes away which leads me to point the finger at react-loading.

**Comment by AJ-Santos** [comment]
@cezary Any thoughts on this issue? I was thinking of giving a PR a try to fix this.

**Comment by cezary** [comment]
It was an issue with the delay and the component being unmounted before the delay, sorry for the long wait.
