### ISSUE TITLE
Color fill not working in ES6 with Webpack

### ISSUE THREAD

**Issue by nmaves** [cezary/react-loading#12]
The loader displays and the delay works but we can't change the color. 

`<Loading type='bars' color='#1e90ff' delay={250} />`

I have attached screen shots of our console.
<img width="1537" alt="hoopla-spa 2" src="https://cloud.githubusercontent.com/assets/367750/13023656/2ad469b8-d1a8-11e5-8092-6e9d5be9fe28.png">
<img width="1544" alt="hoopla-spa" src="https://cloud.githubusercontent.com/assets/367750/13023657/2ad8c4f4-d1a8-11e5-9c02-6d9280a04cfb.png">

**Comment by nmaves** [comment]
Awesome thanks!  Did you already push this to npm as well?

**Comment by cezary** [comment]
No problem. I published it to npm straight away, changes are in 0.0.9.
