### ISSUE TITLE
Cannot read property '__reactAutoBindMap' of null

### ISSUE THREAD

**Issue by tehandyb** [cezary/react-loading#6]
I'm getting this error when I try to use the component in my app. It also comes with these warnings:
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
react-loading.js:6168
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactory

I'm using 0.12.0 with react/addons. So might be a conflict with react versions?

**Comment by josiasds** [comment]
I'm getting it too. Did you manage to solve it?

**Comment by tehandyb** [comment]
I haven't solved it, but I think not including React in the dist file might solve it. I haven't been able to take the time to figure out the changes to the build needs to do it tho.

**Comment by cezary** [comment]
Published a version without the React library in the dist file, let me know if you're still getting these messages.

**Comment by tehandyb** [comment]
I tried doing the npm install react-loading and got this error:
npm WARN package.json react-pill-selector@1.2.1 No repository field.
npm WARN package.json react-sizebox@1.0.0 No repository field.
npm WARN package.json react-xzibit-select@0.2.0 No repository field.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "react-loading"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer fixed-data-table@0.1.2 wants react@>=0.12.0 <0.14.0
npm ERR! peerinvalid Peer react-skylight@0.2.0 wants react@>=0.12.0 <1.0.0
npm ERR! peerinvalid Peer reflux@0.2.8 wants react@>=0.12.2 <0.14.0
npm ERR! peerinvalid Peer react-loading@0.0.7 wants react@>= 0.13.0
npm ERR! peerinvalid Peer react-hot-loader@1.2.7 wants react@>=0.11.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewblowe/Projects/usaid/esdb/npm-debug.log

**Comment by cezary** [comment]
You'll need react 0.13.0; I updated the project so that it extends the Component class instead of using React.createClass. I should probably mention it in the readme.

**Comment by tehandyb** [comment]
Ah I see thanks.

**Comment by tehandyb** [comment]
I'm not familiar with the new es6 syntax, would it be easy for me to change the extend Component class to React.createClass so I can use it with my react 0.12.0 project?
